development:
  adapter: postgresql
  encoding: unicode
  database: perronapp_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: perronapp_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: perronapp_production
  pool: 5
  username:
  password:
